server.servlet.context-path=/

logging.level.org.springframework.web: INFO
logging.level.root: INFO
logging.level.com.jewelbankers:INFO
logging.level.com.zaxxer.hikari=WARN
logging.level.org.springframework.orm.jpa=WARN
logging.level.org.springframework.security=WARN
logging.level.org.hibernate=WARN
logging.level.org.hibernate.orm.query.hql=WARN

# Enable H2 console (if needed)
spring.h2.console.enabled=true

# This should be set to true by default, but just to be sure:
spring.web.resources.add-mappings=true

# MySQL Primary DataSource configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#MySQL Primary DataSource configuration
datasource.primary.url=jdbc:mysql://localhost:3306/jewelbankers_users?allowPublicKeyRetrieval=true&useSSL=false
datasource.primary.username=root
datasource.primary.password=admin


# Secondary Data Source (Example)
datasource.secondary.url=jdbc:mysql://localhost:3306/omji?allowPublicKeyRetrieval=true&useSSL=false
datasource.secondary.username=root
datasource.secondary.password=admin

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

# JPA and Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.type=none
logging.level.org.hibernate.type.descriptor.sql=WARN
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl

# App Properties
bezkoder.app.jwtSecret=_A3GhQMmfixjef5G9bFNKu7XhY7i1Tf5gyuWHrFIVTBk4t9APCX8Foq1SJWgCspLy3MuLgrI7jso0JS65M78dg
bezkoder.app.jwtExpirationMs=86400000


# Google OAuth2 settings
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=roshankag2003@gmail.com
spring.mail.password=YOUR_MAIL_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mySecret.password=YOUR_GOOGLE_CLIENT_SECRET_2


## Twilio Configuration
twilio.account.sid=your_twilio_account_sid
twilio.auth.token=your_twilio_auth_token
twilio.whatsapp.from=whatsapp:+your_twilio_whatsapp_number

file.upload-dir=uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.io.upload.url=""
file.io.auth.token=""

# Allow CORS from specific origins
spring.web.cors.allowed-origin-patterns=http://localhost:4200,http://localhost:8080
spring.web.cors.allow-credentials=true
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*

spring.cache.type=simple  # Use default in-memory cache
spring.cache.cache-names=usersListCache

server.port=8080
#server.ssl.key-store=classpath:jewelbankers.p12
#server.ssl.key-store-password=jewelbankers
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=jewelbankers

excel.type=xlsx
