ALTER TABLE bill_header MODIFY COLUMN BILL_SEQUENCE INT AUTO_INCREMENT;
ALTER TABLE customer MODIFY COLUMN CUSTOMERID INT AUTO_INCREMENT;
ALTER TABLE product_type MODIFY COLUMN product_type_no BIGINT AUTO_INCREMENT;
